apiVersion: v1
kind: Service
metadata:
  name: mlapp-service
  namespace: mlops-visual
  labels:
    app: mlapp
spec:
  selector:
    app: mlapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000